project/server/models/base.py
from project.server import db
from project.server.models.crud import CRUDMixin


class BaseModel(db.Model, CRUDMixin):
    """
    This is the base model that every Sqlalchemy model class should inherit from.
    """
    __abstract__ = True
    pass

project/server/shop/views.py
# project/server/shop/views.py

import typing

from flask import render_template, Blueprint, jsonify, abort, redirect, url_for, flash, session, request

from project.server.extensions import cache
from project.server.models import Manufacturer, DeviceSeries, Device, Customer, Order
from project.server.models.queries import get_bestsellers
from project.server.shop.actions import perform_post_complete_actions
from project.server.shop.forms import SelectRepairForm, RegisterCustomerForm, FinalSubmitForm, MiscForm
from project.tasks.email import notify_shop_about_inquiry
from project.tasks.tricoma import register_tricoma_if_enabled

main_blueprint = Blueprint("shop_blueprint", __name__)


@main_blueprint.route("/")
@main_blueprint.route("/home")
@cache.cached()
def home():
    """
    Render Homepage
    --------------------------------------------------------------
    This site should be cached, because it is the main entry point for many users.
    """
    bestseller: typing.List[Device] = get_bestsellers()
    specialist_manufacturers = Manufacturer.query.filter(
        (Manufacturer.name == "Samsung") | (Manufacturer.name == "Huawei")
    ).all()
    return render_template("shop/home.html", bestseller=bestseller, specialist_manufacturers=specialist_manufacturers)


@main_blueprint.route("/manufacturer")
@cache.cached()
def manufacturer():
    """
    Render a list of all manufacturers as a starting point
    --------------------------------------------------------------
    This site should be cached, because it is the main entry point for many users.
    """
    all_manufacturers: typing.List[Manufacturer] = Manufacturer.query.filter(Manufacturer.activated == True).all()  # noqa
    all_manufacturers_with_repairs = filter(lambda manu: len(manu.series) > 0, all_manufacturers)
    return render_template("shop/manufacturer.html", manufacturers=list(all_manufacturers_with_repairs), manufacturer_names=[manu.name for manu in all_manufacturers_with_repairs])


@main_blueprint.route("/<string:manufacturer_name>")
@main_blueprint.route("/<string:manufacturer_name>/series")
def series(manufacturer_name):
    """ Return all series of the manufacturer, e.g. iPhone, iPad, etc """
    _manufacturer = Manufacturer.query.filter(Manufacturer.name == manufacturer_name).first()
    if not _manufacturer:
        abort(404)
    return render_template("shop/series.html", series=_manufacturer.series, manufacturer=manufacturer_name, series_names=[s.name for s in _manufacturer.series])


@main_blueprint.route("/<string:manufacturer_name>/<string:series_name>")
def all_devices_of_series(manufacturer_name, series_name):
    """ Return all devices of a series, e.g. all iPhones """
    _manufacturer = Manufacturer.query.filter(Manufacturer.name == manufacturer_name).first()
    _series = DeviceSeries.query.filter(DeviceSeries.name == series_name).first()
    if not _manufacturer or not _series:
        abort(404)
    # order devices by order_index with name as a fallback
    _devices = Device.query.filter(Device.series_id == _series.id).order_by(Device.order_index.asc(), Device.name.desc())
    _devices = [device for device in _devices if len(device.repairs)]  # display only devices that have at least one repair
    return render_template("shop/devices.html", devices=_devices, manufacturer=manufacturer_name, series=series_name, device_names=[d.name for d in _devices])


@main_blueprint.route("/<string:manufacturer_name>/<string:series_name>/<string:device_name>/", methods=['GET', 'POST'])
def model(manufacturer_name, series_name, device_name):
    """ Returns the chosen device """
    _manufacturer: Manufacturer = Manufacturer.query.filter(Manufacturer.name == manufacturer_name).first()
    _series: DeviceSeries = DeviceSeries.query.filter(DeviceSeries.name == series_name).first()
    _device: Device = Device.query.filter(Device.name == device_name).first()
    if not _manufacturer or not _series or not _device:
        abort(404)

    repair_form = SelectRepairForm(_device)
    if repair_form.validate_on_submit():
        order = Order.create(
            color=repair_form.get_color(),
            repairs=repair_form.get_repairs(),
            problem_description=repair_form.problem_description.data,
        )
        order.save()
        order.save_to_session()
        return redirect(url_for('.register_customer'))

    return render_template("shop/modell.html", device=_device, repair_form=repair_form, manufacturer=manufacturer_name, series=series_name, repair_names=[f"{rep.device.name} {rep.name}" for rep in _device.repairs])


@main_blueprint.route("/register", methods=['GET', 'POST'])
def register_customer():
    """ Customer enters his/her personal data """
    customer_data_form = RegisterCustomerForm()
    if customer_data_form.validate_on_submit():
        customer = Customer()
        customer_data_form.populate_obj(customer)
        customer.save()
        customer.save_to_session()
        # also register customer in tricoma
        register_tricoma_if_enabled(customer)
        return redirect(url_for('.order_overview'))

    return render_template("shop/customer.html", customer_data_form=customer_data_form)


@main_blueprint.route("/order", methods=['GET', 'POST'])
def order_overview():
    """ A overview about customer data and the repair(s) """
    order: Order = Order.get_from_session()
    if not order or not len(order.repairs) > 0:
        flash("Es wurde noch keine Reparatur ausgewählt", "error")
        return redirect(url_for('.home'))

    customer: Customer = Customer.get_from_session()
    if not customer:
        flash("Sie müssen sich erst registrieren", "warning")
        return redirect(url_for('.register_customer'))

    order.customer = customer
    form = FinalSubmitForm()
    if form.validate_on_submit():
        # ORDER SUBMITTED
        form.populate_order(order)
        order.save()
        perform_post_complete_actions(order)
        return redirect(url_for('.success'))

    return render_template(
        "shop/order.html",
        color=order.color,
        repairs=order.repairs,
        problem_description=order.problem_description,
        device=order.device,
        customer=customer,
        total_cost=order.total_cost,
        taxes=order.taxes,
        discount=order.discount,
        total_cost_including_tax_and_discount=f"{order.total_cost_including_tax_and_discount:.2f}",
        form=form
    )


@main_blueprint.route("/agb")
def agb():
    """ Render Terms and Services """
    return render_template('shop/agb.html')


@main_blueprint.route("/datenschutz")
def datenschutz():
    """ Render Privacy """
    return render_template('shop/datenschutz.html')


@main_blueprint.route("/faq")
def faq():
    """ Render FAQ """
    return render_template('shop/faq.html')


@main_blueprint.route("/impressum")
def impressum():
    """ Render about """
    return render_template('shop/impressum.html')


@main_blueprint.route("/search/<string:device_name>/")
def search(device_name):
    """ Render Search Results """
    found_devices = Device.query.all()
    return render_template('shop/search.html', devices=found_devices)


@main_blueprint.route("/success")
def success():
    """ Render successful order page """
    session.clear()
    return render_template('shop/success.html')


@main_blueprint.route("/referenzen")
def references():
    """ Render references page """
    return render_template('shop/references.html')


@main_blueprint.route("/anfrage", methods=['GET', 'POST'])
def other():
    """ Render other enquiry page """
    form = MiscForm()
    if form.validate_on_submit():
        inquiry = form.create_inquiry()
        notify_shop_about_inquiry(inquiry)
        flash("Danke. Wir haben Ihre Anfrage erhalten!", "success")
        return redirect(url_for(".home"))
    return render_template('shop/other.html', other_inquiry_form=form)


@main_blueprint.route("/api/search/<string:device_name>/")
def search_api(device_name):
    """
    Test endpoint for development
    """
    found_devices_normal = Device.search(device_name).all()
    found_devices_similar = Device.search_order_by_similarity(device_name).all()
    found_devices_array = Device.search_by_array(device_name).all()
    found_devices_levenshtein = Device.search_levenshtein(device_name).all()
    return jsonify(results={
        'normal': [device.name for device in found_devices_normal],
        'similar': [device.name for device in found_devices_similar],
        'array': [device.name for device in found_devices_array],
        'levenshtein': [device.name for device in found_devices_levenshtein],
    })


@main_blueprint.before_request
def check_affiliate():
    """ Check if the customer is a new customer who was redirected by an affiliate. """
    affiliate_track_id = request.args.get('t')
    if affiliate_track_id:
        session['affiliate_track_id'] = affiliate_track_id

project/client/templates/_base.html
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8">
    <title>Smartphoniker - {% block title %}Ihr Service Partner für Smartphone, Tablet oder PC{% endblock %}</title>
    <!-- meta -->
    <meta name="author" content="Leon Morten Richter; Tobias Poertner">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <meta name="keywords" content="Handyreparatur, Smartphone, iPhone, Apple, Samsung, Sony, Display, Akku, Kiel, Smartphoniker, iPad, online, Versand, Garantie">
    <meta property="og:locale" content="de_DE">

    {% block meta %}
        {# Default Description and Title meta tags #}
        <meta name="description" content="Smartphone Reparatur bei ▷ Smartphoniker ✓alle Modelle ✓beste Qualität ✓schneller Service ✓ohne Termin ✆ kostenlose Beratung.">
        <meta property="og:title" content="Smartphone Reparatur Kiel, Schwentinental, Lübeck | Smartphoniker">
        <meta property="og:description" content="Smartphone Reparatur bei ▷ Smartphoniker ✓alle Modelle ✓beste Qualität ✓schneller Service ✓ohne Termin ✆ kostenlose Beratung.">
        <meta property="og:site_name" content="Smartphoniker - Ihr Service Partner für Smartphone, Tablet oder PC">

        <meta name="twitter:description" content="Smartphone Reparatur bei ▷ Smartphoniker ✓alle Modelle ✓beste Qualität ✓schneller Service ✓ohne Termin ✆ kostenlose Beratung.">
        <meta name="twitter:title" content="Smartphone Reparatur Kiel, Schwentinental, Lübeck | Smartphoniker">
    {% endblock %}

    <!-- Favicon -->
    <link rel="icon" type="image/svg+xml" href="{{ url_for('static', filename='favicon/favicon.svg') }}">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon/favicon.ico') }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='favicon/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicon/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ url_for('static', filename='favicon/site.webmanifest') }}">
    <link rel="mask-icon" href="{{ url_for('static', filename='favicon/safari-pinned-tab.svg') }}" color="#ff7100">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon/favicon.ico') }}">
    <meta name="msapplication-TileColor" content="#ff7100">
    <meta name="msapplication-config" content="{{ url_for('static', filename='favicon/browserconfig.xml') }}">
    <meta name="theme-color" content="#ffffff">
    <!-- styles -->
    <link href="{{ url_for('static', filename='css/main.min.css') }}" rel="stylesheet" media="screen">
    {% block css %}{% endblock %}
</head>

<body class="preload">

{% include 'cookie-banner.html' %}
{% include 'header.html' %}

<main>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class="globalerror">
                {% for category, message in messages %}
                    <div class="globalerror__box globalerror__box--{{ category }}">
                        <a class="globalerror__close" title="Close" href="#" data-dismiss="alert">&times;</a>
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
    <!-- child template -->
    {% block content %}{% endblock %}
</main>

{% include 'footer.html' %}

<!-- scripts -->
{% if config['DEBUG'] %}
    {# Dev #}
    <script src="{{ url_for('static', filename='scripts/script.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='scripts/cookie-banner.js') }}" type="text/javascript"></script>
    <script>
        // Cookie Banner Function
        new CookiesEuBanner(function () {
            console.log("analytics accepted");
        }, true);
    </script>
{% else %}
    {# Prod #}
    <script src="{{ url_for('static', filename='scripts/script.min.js') }}" type="text/javascript"></script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-BF14NH0P4R"></script>
    <script src="{{ url_for('static', filename='scripts/cookie-banner.min.js') }}" type="text/javascript"></script>
    <script>
        // Cookie Banner Function
        new CookiesEuBanner(function () {
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
    
            gtag('config', 'G-BF14NH0P4R');
        }, true);
    </script>    
{% endif %}
</body>
</html>

project/client/templates/cookie-banner.html
<!-- Cookie Banner -->
<div id="cookies-eu-banner" style="display: none">
    <p>Wir nutzen für statistische Zwecke Cookies von Google Analytics auf unserer Website. Erfahre <a id="cookies-eu-more" href="{{ url_for('shop_blueprint.datenschutz') }}">hier</a> mehr wie wir für die Sicherheit deiner Daten sorgen.</p>
    
    <button id="cookies-eu-reject">Reject</button>
    <button id="cookies-eu-accept">Accept</button>
</div>

project/client/templates/footer.html
<!--Footer-->
<footer class="container container--wide">
    <div class="footer">
        <ul class="footer__list">
            <li class="footer__item"><a class="footer__link" href="{{ url_for('shop_blueprint.agb') }}">AGB</a></li>
            <li class="footer__item"><a class="footer__link" href="{{ url_for('shop_blueprint.datenschutz') }}">Datenschutz</a></li>
            <li class="footer__item"><a class="footer__link" href="{{ url_for('shop_blueprint.impressum') }}">Impressum</a></li>
        </ul>
        <p class="footer__address">
            <span class="footer__company">Smartphoniker GmbH</span>
            Bahnhofstraße 30 <br>
            24223 Schwentinental
        </p>
        <span class="footer__credit">Made with &#10084; by&nbsp;<a class="footer__credit-links" href="https://leonmortenrichter.de" target="_blank" rel="noreferrer"> Leon </a>&nbsp;&&nbsp;<a class="footer__credit-links" href="https://tobiaspoertner.com" target="_blank" rel="noreferrer">Tobias</a></span>
    </div>
</footer>

project/client/templates/header.html
<!-- Navigation -->
<header class="container container--wide">
    <div class="header">
        <a class="header__logocontainer" href="/">
            <img class="header__logo" src="{{ url_for('static', filename='images/smartphoniker-logo.svg') }}" alt="Smartphoniker Logo">
        </a>

        <nav class="header__nav">
            <a href="#" class="header__togglecontainer hide-desktop">
                <input class="header__menutoggle" type="checkbox" id="menu">
                <span class="header__burgerline"></span>
                <span class="header__burgerline"></span>
                <span class="header__burgerline"></span>
            </a>
            <ul class="header__list show-desktop" id="nav">
                <!-- <li class="header__item"><a class="header__link" href="{{ url_for('shop_blueprint.home') }}">Home</a></li> -->
                <li class="header__item"><a class="header__link" href="{{ url_for('shop_blueprint.manufacturer') }}">Shop</a></li>
                <li class="header__item"><a class="header__link" href="{{ url_for('shop_blueprint.references') }}">Referenzen</a></li>
                <li class="header__item"><a class="header__link" href="{{ url_for('shop_blueprint.faq') }}">FAQ</a></li>
            </ul>
        </nav>
    </div>
</header>

project/client/templates/macros.html
{% macro render_field(field, wrapper_class, msg = null) %}
    <div class="{{ wrapper_class }}">
        <label for="{{ field.name.capitalize() }}" class="customer__label">{{ field.label }}{% if field.flags.required %}<sup>*</sup>{% endif %}</label>
        <input id="{{ field.name.capitalize() }}" class="customer__input" type="{{ field.type }}" name="{{ field.name }}" {% if field.data and field.data|length>0 %}value="{{ field.data }}"{% endif %}">

        <!-- Fehlermeldung -->
        {% for error in field.errors %}
            <p style="display: block;" class="form__error">{{ error }}</p>
        {% endfor %}

        {% if msg %}
            <p id="{{ field.name }}" class="form__error">Bitte geben Sie {{ msg }} an.</p>
        {% endif %}
    </div>
{% endmacro %}