project/server/models/customer.py
# project/server/customer.py
import datetime
import typing

from project.server import db
from project.server.models.session_mixin import SessionStoreMixin
from .crud import CRUDMixin


class Customer(db.Model, CRUDMixin, SessionStoreMixin):
    __tablename__ = "customer"
    SESSION_KW = __tablename__

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    tricoma_id = db.Column(db.String, nullable=True, index=True)
    first_name = db.Column(db.String(255), nullable=True, unique=False, index=True)
    last_name = db.Column(db.String(255), nullable=True, unique=False, index=True)
    tricoma_username = db.Column(db.String(255), nullable=True, unique=False, index=False)
    street = db.Column(db.String(255), nullable=True, unique=False, index=True)
    zip_code = db.Column(db.String(10), nullable=True, unique=False, index=True)
    city = db.Column(db.String(255), nullable=True, unique=False, index=True)
    tel = db.Column(db.String(64), nullable=True, unique=False, index=True)
    email = db.Column(db.String(255), nullable=False, unique=False, index=True)
    registered_on = db.Column(db.DateTime, nullable=False, default=datetime.datetime.now)

    # Relations
    orders = db.relationship("Order", back_populates="customer")
    enquiries = db.relationship("MiscInquiry", back_populates="customer")

    def __repr__(self):
        return self.first_name + " " + self.last_name

    @classmethod
    def deserialize(cls, obj):
        try:
            customer_id = obj['customer_id']
            instance = cls.query.get(customer_id)
            return instance
        except KeyError as error:
            raise ValueError(f"{obj} is an invalid CustomerRepairDTO") from error

    @classmethod
    def query_by_mail(cls, email: str) -> typing.Optional:
        return cls.query.filter(cls.email == email).first()

    def serialize(self) -> dict:
        return dict(
            customer_id=self.id
        )

project/server/models/manufacturer.py
from project.server import db
from project.server.models.base import BaseModel
from project.server.models.image import ImageMixin


class Manufacturer(BaseModel, ImageMixin):
    __tablename__ = "manufacturer"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True, index=True, nullable=False)
    activated = db.Column(db.Boolean(), default=False)

    # Relations
    series = db.relationship("DeviceSeries", back_populates="manufacturer")

    def __repr__(self):
        return self.name

    @property
    def devices(self):
        return [devices for devices in self.series.devices]

    def _get_image_name_for_class(self):
        from project.server.models.image import Image, Default
        return Image.query.filter(Image.manufacturer_default == Default.true).first()  # noqa

project/server/shop/forms.py
import typing

from flask_admin.contrib.sqla.fields import QuerySelectField
from flask_wtf import FlaskForm
from wtforms import SelectField, TextAreaField, SelectMultipleField, StringField, BooleanField, SubmitField, EmailField
from wtforms.validators import DataRequired, Length, Email

from project.server.models import Color, Repair, Shop, Order, Customer
from project.server.models.misc import MiscInquiry


class SelectRepairForm(FlaskForm):
    color = SelectField(
        validators=[DataRequired("Dieses Feld wird benötigt")],
        coerce=int
    )

    repairs = SelectMultipleField(
        validators=[DataRequired("Dieses Feld wird benötigt")],
        coerce=int
    )

    problem_description = TextAreaField(
        validators=[]
    )

    def __init__(self, device, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.color.choices = [(color.id, color) for color in device.colors]
        self.repairs.choices = [(repair.id, repair) for repair in device.repairs]

    def get_color(self) -> typing.Optional[Color]:
        return Color.query.get_or_404(self.color.data)

    def get_repairs(self) -> typing.List[Repair]:
        return [Repair.query.get_or_404(repair_id) for repair_id in self.repairs.data]


class RegisterCustomerForm(FlaskForm):
    first_name = StringField(
        "Vorname",
        validators=[
            DataRequired("Dieses Feld wird benötigt"),
            Length(min=1, max=255, message="Der Name muss zwischen 1 und 255 Zeichen lang sein")
        ]
    )

    last_name = StringField(
        "Nachname",
        validators=[
            DataRequired("Dieses Feld wird benötigt"),
            Length(min=1, max=255, message="Der Name muss zwischen 1 und 255 Zeichen lang sein")
        ]
    )

    street = StringField(
        "Straße",
        validators=[
            DataRequired("Dieses Feld wird benötigt"),
            Length(min=1, max=255, message="Die Straße muss zwischen 1 und 255 Zeichen lang sein")
        ]
    )

    zip_code = StringField(
        "PLZ",
        validators=[
            DataRequired("Dieses Feld wird benötigt"),
            Length(min=3, max=10, message="Die PLZ muss zwischen 3 und 10 Zeichen lang sein")
        ]
    )

    city = StringField(
        "Stadt",
        validators=[
            DataRequired("Dieses Feld wird benötigt"),
            Length(min=1, max=255, message="Die Stadt muss zwischen 1 und 255 Zeichen lang sein")
        ]
    )

    email = EmailField(
        "Email",
        validators=[
            DataRequired("Dieses Feld wird benötigt"),
            Email(message="Bitte gib eine gültige Email Adresse an"),
            Length(min=1, max=64, message="Die Email muss zwischen 1 und 255 Zeichen lang sein")
        ]
    )

    tel = StringField(
        "Telefon",
        validators=[
            Length(min=0, max=64, message="Die Nummer muss zwischen 3 und 64 Zeichen lang sein")
        ]
    )

    tricoma_id = StringField(
        "Kundennummer",
        validators=[
            Length(min=0, max=64, message="Die Nummer muss zwischen 1 und 64 Zeichen lang sein")
        ]
    )


class SelectShopForm(FlaskForm):
    shop = QuerySelectField(
        "Shop",
        query_factory=lambda: Shop.query.all(),
        get_pk=lambda x: x.id,
        get_label=lambda x: x.name,
        validators=[DataRequired("Bitte wähle den Zielshop.")]
    )


class FinalSubmitForm(SelectShopForm):
    shipping_label = BooleanField(
        "Versandlabel",
        default=False
    )

    kva_button = SubmitField(
        "kostenloser Kostenvoranschlag",
        validators=[],
        default=False
    )

    def populate_order(self, order: Order):
        order.kva = self.kva_button.data
        order.complete = True
        order.shop = self.shop.data
        order.customer_wishes_shipping_label = self.shipping_label.data


class MiscForm(FlaskForm):
    first_name = StringField(
        "Vorname",
        validators=[
            DataRequired("Dieses Feld wird benötigt"),
            Length(min=1, max=255, message="Der Name muss zwischen 1 und 255 Zeichen lang sein")
        ]
    )

    last_name = StringField(
        "Name",
        validators=[
            DataRequired("Dieses Feld wird benötigt"),
            Length(min=1, max=255, message="Der Name muss zwischen 1 und 255 Zeichen lang sein")
        ]
    )

    email = EmailField(
        "Mail",
        validators=[
            DataRequired(message="Ohne eine gültige Mail können wir uns nicht zurückmelden"),
            Email(message="Bitte gib eine gültige Email Adresse an"),
            Length(min=1, max=64, message="Die Email muss zwischen 1 und 255 Zeichen lang sein")
        ]
    )

    problem_description = StringField(
        "Beschreibung",
        validators=[
            DataRequired("Bitte gibt eine Beschreibung an."),
            Length(min=30, max=5000, message="Die Beschreibung muss zwischen 30 und 5000 Zeichen lang sein")
        ]
    )

    def create_inquiry(self):
        """ Create a new instance of MiscEnquiry with pre filled customer, description"""
        if not self.validate():
            raise ValueError("Form is invalid")
        customer: Customer = Customer.query_by_mail(self.email.data)
        if not customer:
            customer = Customer.create(email=self.email.data)
        self.populate_obj(customer)
        inquiry = MiscInquiry.create(customer=customer, description=self.problem_description.data)
        return inquiry

project/server/shop/__init__.py
# project/server/shop/__init__.py

project/server/shop/views.py
# project/server/shop/views.py

import typing

from flask import render_template, Blueprint, jsonify, abort, redirect, url_for, flash, session, request

from project.server.extensions import cache
from project.server.models import Manufacturer, DeviceSeries, Device, Customer, Order
from project.server.models.queries import get_bestsellers
from project.server.shop.actions import perform_post_complete_actions
from project.server.shop.forms import SelectRepairForm, RegisterCustomerForm, FinalSubmitForm, MiscForm
from project.tasks.email import notify_shop_about_inquiry
from project.tasks.tricoma import register_tricoma_if_enabled

main_blueprint = Blueprint("shop_blueprint", __name__)


@main_blueprint.route("/")
@main_blueprint.route("/home")
@cache.cached()
def home():
    """
    Render Homepage
    --------------------------------------------------------------
    This site should be cached, because it is the main entry point for many users.
    """
    bestseller: typing.List[Device] = get_bestsellers()
    specialist_manufacturers = Manufacturer.query.filter(
        (Manufacturer.name == "Samsung") | (Manufacturer.name == "Huawei")
    ).all()
    return render_template("shop/home.html", bestseller=bestseller, specialist_manufacturers=specialist_manufacturers)


@main_blueprint.route("/manufacturer")
@cache.cached()
def manufacturer():
    """
    Render a list of all manufacturers as a starting point
    --------------------------------------------------------------
    This site should be cached, because it is the main entry point for many users.
    """
    all_manufacturers: typing.List[Manufacturer] = Manufacturer.query.filter(Manufacturer.activated == True).all()  # noqa
    all_manufacturers_with_repairs = filter(lambda manu: len(manu.series) > 0, all_manufacturers)
    return render_template("shop/manufacturer.html", manufacturers=list(all_manufacturers_with_repairs), manufacturer_names=[manu.name for manu in all_manufacturers_with_repairs])


@main_blueprint.route("/<string:manufacturer_name>")
@main_blueprint.route("/<string:manufacturer_name>/series")
def series(manufacturer_name):
    """ Return all series of the manufacturer, e.g. iPhone, iPad, etc """
    _manufacturer = Manufacturer.query.filter(Manufacturer.name == manufacturer_name).first()
    if not _manufacturer:
        abort(404)
    return render_template("shop/series.html", series=_manufacturer.series, manufacturer=manufacturer_name, series_names=[s.name for s in _manufacturer.series])


@main_blueprint.route("/<string:manufacturer_name>/<string:series_name>")
def all_devices_of_series(manufacturer_name, series_name):
    """ Return all devices of a series, e.g. all iPhones """
    _manufacturer = Manufacturer.query.filter(Manufacturer.name == manufacturer_name).first()
    _series = DeviceSeries.query.filter(DeviceSeries.name == series_name).first()
    if not _manufacturer or not _series:
        abort(404)
    # order devices by order_index with name as a fallback
    _devices = Device.query.filter(Device.series_id == _series.id).order_by(Device.order_index.asc(), Device.name.desc())
    _devices = [device for device in _devices if len(device.repairs)]  # display only devices that have at least one repair
    return render_template("shop/devices.html", devices=_devices, manufacturer=manufacturer_name, series=series_name, device_names=[d.name for d in _devices])


@main_blueprint.route("/<string:manufacturer_name>/<string:series_name>/<string:device_name>/", methods=['GET', 'POST'])
def model(manufacturer_name, series_name, device_name):
    """ Returns the chosen device """
    _manufacturer: Manufacturer = Manufacturer.query.filter(Manufacturer.name == manufacturer_name).first()
    _series: DeviceSeries = DeviceSeries.query.filter(DeviceSeries.name == series_name).first()
    _device: Device = Device.query.filter(Device.name == device_name).first()
    if not _manufacturer or not _series or not _device:
        abort(404)

    repair_form = SelectRepairForm(_device)
    if repair_form.validate_on_submit():
        order = Order.create(
            color=repair_form.get_color(),
            repairs=repair_form.get_repairs(),
            problem_description=repair_form.problem_description.data,
        )
        order.save()
        order.save_to_session()
        return redirect(url_for('.register_customer'))

    return render_template("shop/modell.html", device=_device, repair_form=repair_form, manufacturer=manufacturer_name, series=series_name, repair_names=[f"{rep.device.name} {rep.name}" for rep in _device.repairs])


@main_blueprint.route("/register", methods=['GET', 'POST'])
def register_customer():
    """ Customer enters his/her personal data """
    customer_data_form = RegisterCustomerForm()
    if customer_data_form.validate_on_submit():
        customer = Customer()
        customer_data_form.populate_obj(customer)
        customer.save()
        customer.save_to_session()
        # also register customer in tricoma
        register_tricoma_if_enabled(customer)
        return redirect(url_for('.order_overview'))

    return render_template("shop/customer.html", customer_data_form=customer_data_form)


@main_blueprint.route("/order", methods=['GET', 'POST'])
def order_overview():
    """ A overview about customer data and the repair(s) """
    order: Order = Order.get_from_session()
    if not order or not len(order.repairs) > 0:
        flash("Es wurde noch keine Reparatur ausgewählt", "error")
        return redirect(url_for('.home'))

    customer: Customer = Customer.get_from_session()
    if not customer:
        flash("Sie müssen sich erst registrieren", "warning")
        return redirect(url_for('.register_customer'))

    order.customer = customer
    form = FinalSubmitForm()
    if form.validate_on_submit():
        # ORDER SUBMITTED
        form.populate_order(order)
        order.save()
        perform_post_complete_actions(order)
        return redirect(url_for('.success'))

    return render_template(
        "shop/order.html",
        color=order.color,
        repairs=order.repairs,
        problem_description=order.problem_description,
        device=order.device,
        customer=customer,
        total_cost=order.total_cost,
        taxes=order.taxes,
        discount=order.discount,
        total_cost_including_tax_and_discount=f"{order.total_cost_including_tax_and_discount:.2f}",
        form=form
    )


@main_blueprint.route("/agb")
def agb():
    """ Render Terms and Services """
    return render_template('shop/agb.html')


@main_blueprint.route("/datenschutz")
def datenschutz():
    """ Render Privacy """
    return render_template('shop/datenschutz.html')


@main_blueprint.route("/faq")
def faq():
    """ Render FAQ """
    return render_template('shop/faq.html')


@main_blueprint.route("/impressum")
def impressum():
    """ Render about """
    return render_template('shop/impressum.html')


@main_blueprint.route("/search/<string:device_name>/")
def search(device_name):
    """ Render Search Results """
    found_devices = Device.query.all()
    return render_template('shop/search.html', devices=found_devices)


@main_blueprint.route("/success")
def success():
    """ Render successful order page """
    session.clear()
    return render_template('shop/success.html')


@main_blueprint.route("/referenzen")
def references():
    """ Render references page """
    return render_template('shop/references.html')


@main_blueprint.route("/anfrage", methods=['GET', 'POST'])
def other():
    """ Render other enquiry page """
    form = MiscForm()
    if form.validate_on_submit():
        inquiry = form.create_inquiry()
        notify_shop_about_inquiry(inquiry)
        flash("Danke. Wir haben Ihre Anfrage erhalten!", "success")
        return redirect(url_for(".home"))
    return render_template('shop/other.html', other_inquiry_form=form)


@main_blueprint.route("/api/search/<string:device_name>/")
def search_api(device_name):
    """
    Test endpoint for development
    """
    found_devices_normal = Device.search(device_name).all()
    found_devices_similar = Device.search_order_by_similarity(device_name).all()
    found_devices_array = Device.search_by_array(device_name).all()
    found_devices_levenshtein = Device.search_levenshtein(device_name).all()
    return jsonify(results={
        'normal': [device.name for device in found_devices_normal],
        'similar': [device.name for device in found_devices_similar],
        'array': [device.name for device in found_devices_array],
        'levenshtein': [device.name for device in found_devices_levenshtein],
    })


@main_blueprint.before_request
def check_affiliate():
    """ Check if the customer is a new customer who was redirected by an affiliate. """
    affiliate_track_id = request.args.get('t')
    if affiliate_track_id:
        session['affiliate_track_id'] = affiliate_track_id

project/client/templates/shop/customer.html
{% extends "_base.html" %}
{% from "macros.html" import render_field with context %}


{% block content %}
    <form action="#" method="POST" novalidate>
        {{ customer_data_form.hidden_tag() }}
        <div class="container container--small">
            <section class="hero hero--nocontent">
                <h1 class="hero__heading">Ihre Kontaktdaten</h1>
            </section>
        </div>

        <div class="container container--small">
            {% if customer_data_form.errors %}
            <p style="display: block;" class="form__error form__error--center">Es sind nicht alle Felder korrekt ausgefüllt.</p>
            {% endif %}
            <p id="Error0" class="form__error form__error--center">Es sind nicht alle Felder korrekt ausgefüllt.</p>
        </div>

        <div class="container container--small">
            <section class="customer">
                <h2 class="customer__heading">Persönliche Daten</h2>
                <div class="customer__content">
                    <div class="customer__inputs">
                        {{ render_field(customer_data_form.first_name, "customer__inputwrapper", "Ihren Vornamen") }}
                        {{ render_field(customer_data_form.last_name, "customer__inputwrapper", "Ihren Nachnamen") }}
                    </div>
                </div>
            </section>
        </div>

        <div class="container container--small">
            <hr class="divider">
        </div>

        <div class="container container--small">
            <section class="customer">
                <h2 class="customer__heading">Ihre Adresse</h2>
                <div class="customer__content">
                    <div class="customer__inputs">
                        {{ render_field(customer_data_form.street, "customer__inputwrapper customer__inputwrapper--full", "Ihre Straße & Hausnummer") }}
                        {{ render_field(customer_data_form.zip_code, "customer__inputwrapper customer__inputwrapper--small", "Ihre Postleitzahl") }}
                        {{ render_field(customer_data_form.city, "customer__inputwrapper customer__inputwrapper--small", "Ihren Ort") }}
                    </div>
                </div>
            </section>
        </div>

        <div class="container container--small">
            <hr class="divider">
        </div>

        <div class="container container--small">
            <section class="customer">
                <h2 class="customer__heading">Wie können wir Sie erreichen?</h2>
                <div class="customer__content customer__content--infosection">
                    <div class="customer__inputs">
                        {{ render_field(customer_data_form.email, "customer__inputwrapper", "eine gültige Email") }}
                        {{ render_field(customer_data_form.tel, "customer__inputwrapper") }}
                        {{ render_field(customer_data_form.tricoma_id, "customer__inputwrapper customer__inputwrapper customer__inputwrapper--small") }}
                        <div class="customer__buttonwrapper">
                            <button id="Submit" class="customer__button">Zur Bestellübersicht</button>
                        </div>
                    </div>
                    <div class="customer__infowrapper">
                        <p class="customer__text"><sup>*</sup> = Feld ist erforderlich</p>
                        <p class="customer__text">Ihre Adresse und Ihre Kontaktdaten werden einerseits zur Identifikation und Zuordnung verwendet und andererseits um Rückfragen für Sie möglichst bequem zu gestalten. </p>
                        <p class="customer__text">Über Ihre Mail-Adresse erhalten Sie zudem laufende Informationen zum Status Ihrer Reparatur.</p>
                    </div>
                </div>
            </section>
        </div>

    </form>
{% endblock %}

project/client/templates/shop/home.html
{% extends "_base.html" %}
{% block content %}
    <style>
        body {
            background-repeat: no-repeat;
            background-image: url("{{ url_for('static', filename='images/heroimage.jpg') }}");
            background-size: 800px;
            background-position: top;
        }

        @media screen and (min-width: 650px) {
            body {
                background-position-y: inherit;
            }
        }

        @media screen and (min-width: 800px) {
            body {
                background-size: 900px;
                background-position-y: -3%;
            }
        }

        @media screen and (min-width: 900px) {
            body {
                background-image: url("{{ url_for('static', filename='images/heroimage-wide.jpg') }}");
                background-size: 1920px;
                background-position-y: inherit;
                background-position-x: 62%;
                max-height: none;
            }
        }

        @media screen and (min-width: 1250px) {
            body {
                background-position-y: -2%;
            }
        }

        @media screen and (min-width: 1920px) {
            body {
                background-size: 2560px;
                background-position-y: -5%;
            }
        }

        @media screen and (min-width: 2560px) {
            body {
                background-size: 3440px;
                background-position-y: -15%;
            }
        }
    </style>
    <div class="container container--small container--heroimage">
        <section class="hero">
            <h1 class="hero__heading hero__heading--home">Professionelle&thinsp;Handy-Reparatur</h1>
            <p class="hero__subheading">
                Bildschirm kaputt? Akku schwach? <br class="hide-desktop">
                Niemand versteht dich mehr? <br class="hide-desktop">
                Kein Problem, lass das den <br class="hide-desktop">
                Smartphoniker machen! <br class="hide-desktop">
                <span class="hide-mobile">Wir reparieren dein Handy in
                        sehr kurzer Zeit. Egal ob iPhone, Samsung, Huawei
                        oder ganz was anderes. Hier bist du richtig!</span>
            </p>
            <a class="hero__cta" href="{{ url_for('shop_blueprint.manufacturer') }}">Gerät auswählen</a>
        </section>
    </div>

    <div class="container container--small ">
        <section class="bestseller">
            <h2 class="bestseller__heading">Top Geräte</h2>
            <div class="bestseller__content">
                <ul class="bestseller__list">
                    {% for seller in bestseller %}
                        <li class="bestseller__item">
                            <img class="bestseller__img" src="{{ seller.get_image_path() }}" alt="{{ seller.name }}">
                            <a class="bestseller__link" href="{{ url_for('shop_blueprint.model', manufacturer_name=seller.manufacturer.name, series_name=seller.series.name, device_name=seller.name) }}">
                                <h3 class="bestseller__devicename">{{ seller.name }}</h3>
                            </a>
                        </li>
                    {% endfor %}
                    <li class="bestseller__item">
                        <p class="bestseller__text">Dein Gerät ist <br> nicht dabei?</p>
                        <a class="bestseller__cta" href="{{ url_for('.manufacturer') }}">Alle ansehen</a>
                    </li>
                </ul>
            </div>
        </section>
    </div>

    


    <div class="container container--brands">
        <section class="brands">
            <h2 class="brands__heading">Spezialist für:</h2>
            <div class="brands__content">
                <ul class="brands__list">
                    {% for manu in specialist_manufacturers %}
                        <li class="brands__item">
                            <a class="brands__link" href="{{ url_for('shop_blueprint.series', manufacturer_name=manu.name) }}">
                                {% if manu.get_image_path() %}
                                    <img class="brands__img" src="{{ manu.get_image_path() }}" alt="show {{ manu.name }} devices">
                                {% else %}
                                    {{ manu.name }}
                                {% endif %}
                            </a>
                        </li>
                    {% endfor %}
                    <li class="brands__item"><a class="brands__link" href="{{ url_for('shop_blueprint.manufacturer') }}">Viele<br>mehr</a></li>
                </ul>
            </div>
        </section>
    </div>

    <div class="container container--small container--dual">
        <section class="testimonial">
            <h2 class="testimonial__heading">Das sagen Kunden</h2>
            <div class="testimonial__content">
                <a class="testimonial__link" target="_blank" href="https://g.page/Smartphoniker-Express-S?gm" rel="noopener">
                    <img class="testimonial__img" src="{{ url_for('static', filename="images/googlerating.svg") }}" alt="Google Bewertungen">
                </a>
            </div>
        </section>
        <section class="faq-section">
            <h2 class="faq-section__heading">FAQ</h2>
            <div class="faq-section__content">
                <ul class="faq-section__list">
                    <li class="faq-section__item"><a class="faq-section__link" href="{{ url_for('.faq', q=17) }}">Wie lange dauert die Reparatur?</a></li>
                    <li class="faq-section__item"><a class="faq-section__link" href="{{ url_for('.faq', q=15) }}">Benutzt ihr Originale Ersatzteile?</a></li>
                    <li class="faq-section__item"><a class="faq-section__link" href="{{ url_for('.faq', q=28) }}">Gibt es eine Garantie auf die Reparatur?</a></li>
                    <li class="faq-section__item"><a class="faq-section__link" href="{{ url_for('.faq', q=8) }}">Welche Bezahlungsmethoden gibt es?</a></li>
                    <li class="faq-section__item"><a class="faq-section__link" href="{{ url_for('.faq', q=29) }}">Was ist, wenn ich nach der Reparatur Probleme habe?</a></li>
                </ul>
            </div>
        </section>
    </div>

    <div class="container container--brands">
        <div class="container container--small ">
            <section class="bestseller">
                <h2 class="bestseller__heading">So läuft die Reparatur ab:</h2>
                <div class="bestseller__content">
                    <img src="{{ url_for('static', filename="images/repair_process.svg") }}" alt="Reparatur-Prozess">
                </div>
            </section>
        </div>
    </div>
{% endblock %}

project/client/templates/shop/impressum.html
{% extends "_base.html" %}
{% block title %}
    Impressum
{% endblock %}

{% block content %}
    <div class="container container--small">
        <section class="hero hero--nocontent">
            <h1 class="hero__heading">Impressum</h1>
        </section>
    </div>

    <div class="container container--small">
        <section class="datagb">
            <h2 class="datagb__heading">Verantwortlich</h2>
                <p class="datagb__text"><strong class="datagb__company">Smartphoniker GmbH</strong> <br> Bahnhofstraße 30 <br>24223 Schwentinental <br> Deutschland</p>
                <p class="datagb__text">
                    Tel. <a class="datagb__link" href="tel: 4943190700390">+49 431 90 700 390</a><br>
                    E-Mail: <a class="datagb__link" href="mailto: info@smartphoniker.de">info@smartphoniker.de</a>
                </p>
                <p class="datagb__text">Geschäftsführende Gesellschafter: <br> Felix Vollstedt, Benedikt Görges</p>
                <p class="datagb__text">Amtsgericht Kiel, HRB 17855 KI <br> Umsatzsteuer-ID: DE306739068</p>
                <p class="datagb__text">Verantwortlicher Ansprechpartner für diese Website: Benedikt Görges</p>
                <p class="datagb__text">
                    Hier erreichen Sie die Plattform der EZ zur außergerichtlichen Online-Streitbeilegung: <br>
                    <a class="datagb__link" href="http://ec.europa.eu/consumers/odr/">http://ec.europa.eu/consumers/odr/</a>
                </p>
        </section>
    </div>
{% endblock %}

project/client/templates/shop/search.html
{% extends "_base.html" %}
{% block content %}
<div class="container container--small">
    <section class="hero hero--nocontent">
        <h1 class="hero__heading">Schnellsuche</h1>
        <p class="hero__chronic hide-mobile">
            <a class="hero__chroniclink" href="{{ url_for('.shop') }}">Shop</a> > <a class="hero__chroniclink" href="{{ url_for('.search', device_name='all') }}">Suche</a> > <a class="hero__chroniclink" href="{{ url_for('.search', device_name=search) }}">{{ search }}</a>
        </p>
    </section>
</div>

<div class="container container--small">
    <section class="search">
        <h2 class="search__heading"><label for="Search">Suchbegriff eingeben</label></h2>
        <div class="search__content">
            <input id="Search" class="search__input" type="text" placeholder="Geben Sie hier Ihre Gerätebezeichnung ein" value="{{ search }}">
            <a id="Submit" class="search__button">Suchen</a>
        </div>
    </section>
</div>

<div class="container container--small">
    <hr class="divider">
</div>

<div class="container container--small">
    <section class="grid">
        <h2 class="grid__heading">Suchergebnisse</h2>
        <div class="grid__content">
                {% for device in devices %}
                    <div class="grid__item">
                        <a class="grid__link" href="#">
                            {% if device.image %}
                                <img class="grid__image" src="{{ manu.get_image_path() }}" alt="{{ manu.name }} auswählen">
                            {% endif %}
                            <div>{{ device.name }}</div>
                        </a>
                    </div>
                {% endfor %}
        </div>
    </section>
</div>
{% endblock %}