project/server/models/device.py
import typing

from sqlalchemy import Index, desc, func, any_, bindparam, asc

from project.server import db
from project.server.models.crud import CRUDMixin
from project.server.models.image import ImageMixin
from project.server.models.orderable import OrderableMixin

color_device_table = db.Table('color_device',
                              db.Column('color_id', db.Integer, db.ForeignKey('color.id')),
                              db.Column('device_id', db.Integer, db.ForeignKey('device.id'))
                              )


class Color(db.Model, CRUDMixin):
    __tablename__ = 'color'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128), nullable=False)  # public name that is displayed to user's
    internal_name = db.Column(db.String(128), index=True, unique=True, nullable=False)  # internal name that we use to map colors to manufacturers
    color_code = db.Column(db.String(20), nullable=False)
    devices = db.relationship(
        "Device",
        secondary=color_device_table,
        back_populates="colors")

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.internal_name


class Device(db.Model, CRUDMixin, ImageMixin, OrderableMixin):
    __tablename__ = "device"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    is_tablet = db.Column(db.Boolean(), default=False)

    # Relations
    series_id = db.Column(db.Integer, db.ForeignKey('device_series.id'), nullable=False)
    series = db.relationship("DeviceSeries")

    colors = db.relationship(
        "Color",
        secondary=color_device_table,
        back_populates="devices"
    )

    repairs = db.relationship("Repair", back_populates="device", cascade="all, delete-orphan",
                              order_by='Repair.order_index.asc()')

    __table_args__ = (
        Index(
            'name_idx', "name",
            postgresql_ops={"name": "gin_trgm_ops"},
            postgresql_using='gin'),
    )

    @classmethod
    def search(cls, q: str):
        """
        This method fuzzy searches the Device.name column.
        ----------
        SELECT * FROM devices WHERE name % 'SEARCH_KW';
        ----------
        """
        query = cls.query.filter(Device.name.op('%%')(q))
        return query

    @classmethod
    def search_order_by_similarity(cls, q: str):
        """
        SELECT * FROM devices WHERE name % 'SEARCH_KW' ORDER BY SIMILARITY(name, 'IPHONE 11') DESC;
        """
        query = cls.search(q)
        query = query.order_by(desc(func.similarity(cls.name, q)))
        return query

    @classmethod
    def search_by_array(cls, q: str):
        """
        SELECT * FROM devices WHERE 'X' % ANY(STRING_TO_ARRAY(name, ' '));
        """
        query = cls.query.filter(
            bindparam('string', q).op('%%')(any_(func.string_to_array(Device.name, ' ')))
        )
        return query

    @classmethod
    def search_levenshtein(cls, q: str, limit: int = 15):
        """
        SELECT * from devices order by LEVENSHTEIN(name, '11') ASC;
        """
        query = cls.query.order_by(asc(func.levenshtein(Device.name, q))).limit(limit)
        return query

    @classmethod
    def merge(cls, ids: typing.List[int]):
        """ Merge a list of devices (id's) into a one. Heavily opinionated method."""
        query = cls.query.filter(cls.id.in_(ids))
        with cls.session():
            # Copy basic data from the first device
            merger = _create_from_first_device(query[0])
            # Get the first non none image
            merger.image = next(filter(lambda i: i is not None, map(lambda d: d.image, query.all())), None)
            for device in query:
                # merge relations
                _merge_colors(merger, device.colors)
                _merge_repairs(merger, device.repairs)
                # dont forget to delete
                device.delete()
            merger.name = merger.name[:-1]
            return merger

    @property
    def manufacturer(self):
        return self.series.manufacturer

    def __repr__(self):
        return self.name or "n.a"

    def _get_image_name_for_class(self):
        from project.server.models.image import Image, Default
        if self.is_tablet:
            return Image.query.filter(Image.tablet_default == Default.true).first()  # noqa
        return Image.query.filter(Image.device_default == Default.true).first()  # noqa


def _create_from_first_device(first: Device) -> Device:
    name, is_tablet, series = first.name, first.is_tablet, first.series
    merger = Device.create(name=name + "#", is_tablet=is_tablet, series=series)
    return merger


def _merge_colors(merger: Device, colors: typing.List) -> None:
    for color in colors:
        if color not in merger.colors:
            merger.colors.append(color)


def _merge_repairs(merger: Device, repairs: typing.List) -> None:
    for repair in repairs:
        if repair.name not in map(lambda d: d.name, merger.repairs):
            rep = repair.clone()
            rep.device = merger
            rep.save()
            repair.delete()

project/server/models/manufacturer.py
from project.server import db
from project.server.models.base import BaseModel
from project.server.models.image import ImageMixin


class Manufacturer(BaseModel, ImageMixin):
    __tablename__ = "manufacturer"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True, index=True, nullable=False)
    activated = db.Column(db.Boolean(), default=False)

    # Relations
    series = db.relationship("DeviceSeries", back_populates="manufacturer")

    def __repr__(self):
        return self.name

    @property
    def devices(self):
        return [devices for devices in self.series.devices]

    def _get_image_name_for_class(self):
        from project.server.models.image import Image, Default
        return Image.query.filter(Image.manufacturer_default == Default.true).first()  # noqa

project/server/models/series.py
from project.server import db
from project.server.models.base import BaseModel


class DeviceSeries(BaseModel):
    """ Association table between Device and Manufacturer """
    __tablename__ = "device_series"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True, index=True, nullable=False)

    # Relations
    manufacturer_id = db.Column(db.Integer, db.ForeignKey('manufacturer.id'), nullable=False)
    manufacturer = db.relationship("Manufacturer")

    devices = db.relationship("Device", back_populates="series")

    def __repr__(self):
        return self.name

project/server/main/views.py
# project/server/main/views.py

import typing

from flask import render_template, Blueprint, jsonify, abort, redirect, url_for, flash, session, request

from project.server.common.referral import is_referred_user, save_referral_to_session, REF_ID_KW, create_referral_if_applicable
from project.server.main.forms import SelectRepairForm, RegisterCustomerForm, FinalSubmitForm, MiscForm
from project.server.models import Manufacturer, DeviceSeries, Device, Customer, Order
from project.server.models.queries import get_bestsellers
from project.tasks.email import notify_shop_about_inquiry
from project.tasks.tricoma import register_tricoma_if_enabled

main_blueprint = Blueprint("main", __name__)


@main_blueprint.route("/")
@main_blueprint.route("/home")
def home():
    """ Render Homepage """
    bestseller: typing.List[Device] = get_bestsellers()
    specialist_manufacturers = Manufacturer.query.filter(
        (Manufacturer.name == "Apple") | (Manufacturer.name == "Samsung") | (Manufacturer.name == "Huawei")
    ).all()
    return render_template("main/home.html", bestseller=bestseller, specialist_manufacturers=specialist_manufacturers)


@main_blueprint.route("/manufacturer")
def manufacturer():
    """ Render a list of all manufacturers as a starting point """
    all_manufacturers: [Manufacturer] = Manufacturer.query.filter(Manufacturer.activated == True).all()  # noqa
    all_manufacturers_with_repairs = filter(lambda manu: len(manu.series) > 0, all_manufacturers)
    return render_template("main/manufacturer.html", manufacturers=list(all_manufacturers_with_repairs), manufacturer_names=[manu.name for manu in all_manufacturers_with_repairs])


@main_blueprint.route("/<string:manufacturer_name>/series")
def series(manufacturer_name):
    """ Return all series of the manufacturer, e.g. iPhone, iPad, etc """
    _manufacturer = Manufacturer.query.filter(Manufacturer.name == manufacturer_name).first()
    if not _manufacturer:
        abort(404)
    return render_template("main/series.html", series=_manufacturer.series, manufacturer=manufacturer_name, series_names=[s.name for s in _manufacturer.series])


@main_blueprint.route("/<string:manufacturer_name>/<string:series_name>")
def all_devices_of_series(manufacturer_name, series_name):
    """ Return all devices of a series, e.g. all iPhones """
    _manufacturer = Manufacturer.query.filter(Manufacturer.name == manufacturer_name).first()
    _series = DeviceSeries.query.filter(DeviceSeries.name == series_name).first()
    if not _manufacturer or not _series:
        abort(404)
    # order devices by order_index with name as a fallback
    _devices = Device.query.filter(Device.series_id == _series.id).order_by(Device.order_index.asc(), Device.name.desc())
    _devices = [device for device in _devices if len(device.repairs)]  # display only devices that have at least one repair
    return render_template("main/devices.html", devices=_devices, manufacturer=manufacturer_name, series=series_name, device_names=[d.name for d in _devices])


@main_blueprint.route("/<string:manufacturer_name>/<string:series_name>/<string:device_name>/", methods=['GET', 'POST'])
def model(manufacturer_name, series_name, device_name):
    """ Returns the chosen device """
    _manufacturer: Manufacturer = Manufacturer.query.filter(Manufacturer.name == manufacturer_name).first()
    _series: DeviceSeries = DeviceSeries.query.filter(DeviceSeries.name == series_name).first()
    _device: Device = Device.query.filter(Device.name == device_name).first()
    if not _manufacturer or not _series or not _device:
        abort(404)

    repair_form = SelectRepairForm(_device)
    if repair_form.validate_on_submit():
        order = Order.create(
            color=repair_form.get_color(),
            repairs=repair_form.get_repairs(),
            problem_description=repair_form.problem_description.data,
        )
        order.save()
        order.save_to_session()
        return redirect(url_for('main.register_customer'))

    return render_template("main/modell.html", device=_device, repair_form=repair_form, manufacturer=manufacturer_name, series=series_name, repair_names=[f"{rep.device.name} {rep.name}" for rep in _device.repairs])


@main_blueprint.route("/register", methods=['GET', 'POST'])
def register_customer():
    """ Customer enters his/her personal data """
    customer_data_form = RegisterCustomerForm()
    if customer_data_form.validate_on_submit():
        customer = Customer()
        customer_data_form.populate_obj(customer)
        customer.save()
        customer.save_to_session()
        # also register customer in tricoma
        register_tricoma_if_enabled(customer)
        return redirect(url_for('main.order_overview'))

    return render_template("main/customer.html", customer_data_form=customer_data_form)


@main_blueprint.route("/order", methods=['GET', 'POST'])
def order_overview():
    """ A overview about customer data and the repair(s) """
    order: Order = Order.get_from_session()
    if not order or not len(order.repairs) > 0:
        flash("Es wurde noch keine Reparatur ausgewählt", "error")
        return redirect(url_for('main.home'))

    customer: Customer = Customer.get_from_session()
    if not customer:
        flash("Sie müssen sich erst registrieren", "warning")
        return redirect(url_for('main.register_customer'))

    order.customer = customer
    form = FinalSubmitForm()
    if form.validate_on_submit():
        # ORDER SUBMITTED
        form.populate_order(order)
        order.save()
        order.notify()
        create_referral_if_applicable(order)
        return redirect(url_for('main.success'))

    return render_template(
        "main/order.html",
        color=order.color,
        repairs=order.repairs,
        problem_description=order.problem_description,
        device=order.device,
        customer=customer,
        total_cost=order.total_cost,
        taxes=order.taxes,
        discount=order.discount,
        total_cost_including_tax_and_discount=f"{order.total_cost_including_tax_and_discount:.2f}",
        form=form
    )


@main_blueprint.route("/agb")
def agb():
    """ Render Terms and Services """
    return render_template('main/agb.html')


@main_blueprint.route("/datenschutz")
def datenschutz():
    """ Render Privacy """
    return render_template('main/datenschutz.html')


@main_blueprint.route("/faq")
def faq():
    """ Render FAQ """
    return render_template('main/faq.html')


@main_blueprint.route("/impressum")
def impressum():
    """ Render about """
    return render_template('main/impressum.html')


@main_blueprint.route("/search/<string:device_name>/")
def search(device_name):
    """ Render Search Results """
    found_devices = Device.query.all()
    return render_template('main/search.html', devices=found_devices)


@main_blueprint.route("/success")
def success():
    """ Render successful order page """
    session.clear()
    return render_template('main/success.html')


@main_blueprint.route("/referenzen")
def references():
    """ Render references page """
    return render_template('main/references.html')


@main_blueprint.route("/anfrage", methods=['GET', 'POST'])
def other():
    """ Render other enquiry page """
    form = MiscForm()
    if form.validate_on_submit():
        inquiry = form.create_model()
        notify_shop_about_inquiry(inquiry)
        flash("Danke. Wir haben Ihre Anfrage erhalten!", "success")
        return redirect(url_for("main.home"))
    return render_template('main/other.html', other_inquiry_form=form)


@main_blueprint.route("/api/search/<string:device_name>/")
def search_api(device_name):
    """
    Test endpoint for development
    """
    found_devices_normal = Device.search(device_name).all()
    found_devices_similar = Device.search_order_by_similarity(device_name).all()
    found_devices_array = Device.search_by_array(device_name).all()
    found_devices_levenshtein = Device.search_levenshtein(device_name).all()
    return jsonify(results={
        'normal': [device.name for device in found_devices_normal],
        'similar': [device.name for device in found_devices_similar],
        'array': [device.name for device in found_devices_array],
        'levenshtein': [device.name for device in found_devices_levenshtein],
    })


@main_blueprint.before_request
def check_referral():
    """ Check if the customer is a new customer who was redirected by a ref link. """
    if is_referred_user(request.args):
        save_referral_to_session(request.args[REF_ID_KW])

project/client/templates/main/devices.html
{% extends "_base.html" %}
{% block meta %}
    {% set name_string = device_names|join(", ") %}
    <meta name="description" content="{{ name_string }} in Kiel, Schwentinental, Lübeck bei ▷ Smartphoniker ✓alle Modelle ✓beste Qualität ✓schneller Service ✓ohne Termin ✆ kostenlose Beratung.">
    <meta property="og:title" content="{{ name_string }} Smartphone Reparatur Kiel, Schwentinental, Lübeck | Smartphoniker">
    <meta property="og:description" content="{{ name_string }} bei ▷ Smartphoniker ✓alle Modelle ✓beste Qualität ✓schneller Service ✓ohne Termin ✆ kostenlose Beratung.">
    <meta property="og:site_name" content="Smartphoniker - Ihr Service Partner für Smartphone, Tablet oder PC">

    <meta name="twitter:description" content="{{ name_string }} bei ▷ Smartphoniker ✓alle Modelle ✓beste Qualität ✓schneller Service ✓ohne Termin ✆ kostenlose Beratung.">
    <meta name="twitter:title" content="{{ name_string }} Kiel, Schwentinental, Lübeck | Smartphoniker">
{% endblock %}

{% block content %}
    <div class="container container--small">
        <section class="hero">
            <h1 class="hero__heading">Alle Hersteller</h1>
            <p class="hero__chronic hide-mobile">
                <a class="hero__chroniclink" href="{{ url_for('main.manufacturer') }}">Hersteller auswählen</a> >
                <a class="hero__chroniclink" href="{{ url_for('main.series', manufacturer_name=manufacturer) }}">Serie auswählen</a>
            </p>
            <div class="progressbar">
                <div class="progressbar__step">
                    <div class="progressbar__number progressbar__number--active">1</div>
                    <div class="progressbar__text">Hersteller wählen</div>
                </div>
                <div class="progressbar__divider"></div>
                <div class="progressbar__step">
                    <div id="STEP2" class="progressbar__number progressbar__number--active">2</div>
                    <div class="progressbar__text">Modellreihe bestimmen</div>
                </div>
                <div class="progressbar__divider"></div>
                <div class="progressbar__step">
                    <div id="STEP3" class="progressbar__number progressbar__number--active">3</div>
                    <div class="progressbar__text">Gerät auswählen</div>
                </div>
            </div>
        </section>
    </div>

    <div class="container container--small">
        <section class="grid">
            <h2 class="grid__heading">Modell wählen</h2>
            <div class="grid__content grid__content--longlist">
                {% for device in devices %}
                    <div class="grid__item">
                        <a class="grid__link" href="{{ url_for('main.model', manufacturer_name=manufacturer, series_name=series, device_name=device.name) }}">
                            {% if device.get_image() %}
                                <img class="grid__image" src="{{ device.get_image_path() }}" alt="{{ device.name }} auswählen">
                            {% endif %}
                            <div class="grid__image">{{ device.name }}</div>
                        </a>
                    </div>
                {% endfor %}
            </div>
            {% if not devices|length %}
                <p class="grid__nodevices">Aktuell bieten wir keine Festpreise für Reparaturen dieser Serie an. Melden Sie sich gerne bei unserem <a class="grid__link grid__link--inline" href="{{ url_for('main.faq', q='38') }}">Kundenservice</a>, wenn Sie an einer Reparatur interessiert sind.</p>
                <a class="grid__back" href="{{ url_for('main.series', manufacturer_name=manufacturer) }}">zurück zu den Serien</a>
            {% endif %}

        </section>
    </div>
{% endblock %}

project/client/templates/main/home.html
{% extends "_base.html" %}
{% block content %}
    <style>
        body {
            background-repeat: no-repeat;
            background-image: url("{{ url_for('static', filename='images/heroimage.jpg') }}");
            background-size: 800px;
            background-position: top;
        }

        @media screen and (min-width: 650px) {
            body {
                background-position-y: inherit;
            }
        }

        @media screen and (min-width: 800px) {
            body {
                background-size: 900px;
                background-position-y: -3%;
            }
        }

        @media screen and (min-width: 900px) {
            body {
                background-image: url("{{ url_for('static', filename='images/heroimage-wide.jpg') }}");
                background-size: 1920px;
                background-position-y: inherit;
                background-position-x: 62%;
                max-height: none;
            }
        }

        @media screen and (min-width: 1250px) {
            body {
                background-position-y: -2%;
            }
        }

        @media screen and (min-width: 1920px) {
            body {
                background-size: 2560px;
                background-position-y: -5%;
            }
        }

        @media screen and (min-width: 2560px) {
            body {
                background-size: 3440px;
                background-position-y: -15%;
            }
        }
    </style>
    <div class="container container--small container--heroimage">
        <section class="hero">
            <h1 class="hero__heading hero__heading--home">Professionelle&thinsp;Handy-Reparatur</h1>
            <p class="hero__subheading">
                Bildschirm kaputt? Akku schwach? <br class="hide-desktop">
                Niemand versteht dich mehr? <br class="hide-desktop">
                Kein Problem, lass das den <br class="hide-desktop">
                Smartphoniker machen! <br class="hide-desktop">
                <span class="hide-mobile">Wir reparieren dein Handy in
                        sehr kurzer Zeit. Egal ob iPhone, Samsung, Huawei
                        oder ganz was anderes. Hier bist du richtig!</span>
            </p>
            <a class="hero__cta" href="{{ url_for('main.manufacturer') }}">Gerät auswählen</a>
        </section>
    </div>

    <div class="container container--small ">
        <section class="bestseller">
            <h2 class="bestseller__heading">Top Geräte</h2>
            <div class="bestseller__content">
                <ul class="bestseller__list">
                    {% for seller in bestseller %}
                        <li class="bestseller__item">
                            <img class="bestseller__img" src="{{ seller.get_image_path() }}" alt="{{ seller.name }}">
                            <a class="bestseller__link" href="{{ url_for('main.model', manufacturer_name=seller.manufacturer.name, series_name=seller.series.name, device_name=seller.name) }}">
                                <h3 class="bestseller__devicename">{{ seller.name }}</h3>
                            </a>
                        </li>
                    {% endfor %}
                    <li class="bestseller__item">
                        <p class="bestseller__text">Dein Gerät ist <br> nicht dabei?</p>
                        <a class="bestseller__cta" href="{{ url_for('.manufacturer') }}">Alle ansehen</a>
                    </li>
                </ul>
            </div>
        </section>
    </div>

    <div class="container container--brands">
        <section class="brands">
            <h2 class="brands__heading">Spezialist für:</h2>
            <div class="brands__content">
                <ul class="brands__list">
                    {% for manu in specialist_manufacturers %}
                        <li class="brands__item">
                            <a class="brands__link" href="{{ url_for('main.series', manufacturer_name=manu.name) }}">
                                {% if manu.get_image_path() %}
                                    <img class="brands__img" src="{{ manu.get_image_path() }}" alt="show {{ manu.name }} devices">
                                {% else %}
                                    {{ manu.name }}
                                {% endif %}
                            </a>
                        </li>
                    {% endfor %}
                    <li class="brands__item"><a class="brands__link" href="{{ url_for('main.manufacturer') }}">Viele<br>mehr</a></li>
                </ul>
            </div>
        </section>
    </div>

    <div class="container container--small container--dual">
        <section class="testimonial">
            <h2 class="testimonial__heading">Das sagen Kunden</h2>
            <div class="testimonial__content">
                <a class="testimonial__link" target="_blank" href="https://g.page/Smartphoniker-Express-S?gm" rel="noopener">
                    <img class="testimonial__img" src="{{ url_for('static', filename="images/googlerating.svg") }}" alt="Google Bewertungen">
                </a>
            </div>
        </section>
        <section class="faq-section">
            <h2 class="faq-section__heading">FAQ</h2>
            <div class="faq-section__content">
                <ul class="faq-section__list">
                    <li class="faq-section__item"><a class="faq-section__link" href="{{ url_for('.faq', q=17) }}">Wie lange dauert die Reparatur?</a></li>
                    <li class="faq-section__item"><a class="faq-section__link" href="{{ url_for('.faq', q=15) }}">Benutzt ihr Originale Ersatzteile?</a></li>
                    <li class="faq-section__item"><a class="faq-section__link" href="{{ url_for('.faq', q=28) }}">Gibt es eine Garantie auf die Reparatur?</a></li>
                    <li class="faq-section__item"><a class="faq-section__link" href="{{ url_for('.faq', q=8) }}">Welche Bezahlungsmethoden gibt es?</a></li>
                    <li class="faq-section__item"><a class="faq-section__link" href="{{ url_for('.faq', q=29) }}">Was ist, wenn ich nach der Reparatur Probleme habe?</a></li>
                </ul>
            </div>
        </section>
    </div>
{% endblock %}

project/client/templates/main/search.html
{% extends "_base.html" %}
{% block content %}
<div class="container container--small">
    <section class="hero hero--nocontent">
        <h1 class="hero__heading">Schnellsuche</h1>
        <p class="hero__chronic hide-mobile">
            <a class="hero__chroniclink" href="{{ url_for('main.shop') }}">Shop</a> > <a class="hero__chroniclink" href="{{ url_for('main.search', device_name='all') }}">Suche</a> > <a class="hero__chroniclink" href="{{ url_for('main.search', device_name=search) }}">{{ search }}</a>
        </p>
    </section>
</div>

<div class="container container--small">
    <section class="search">
        <h2 class="search__heading"><label for="Search">Suchbegriff eingeben</label></h2>
        <div class="search__content">
            <input id="Search" class="search__input" type="text" placeholder="Geben Sie hier Ihre Gerätebezeichnung ein" value="{{ search }}">
            <a id="Submit" class="search__button">Suchen</a>
        </div>
    </section>
</div>

<div class="container container--small">
    <hr class="divider">
</div>

<div class="container container--small">
    <section class="grid">
        <h2 class="grid__heading">Suchergebnisse</h2>
        <div class="grid__content">
                {% for device in devices %}
                    <div class="grid__item">
                        <a class="grid__link" href="#">
                            {% if device.image %}
                                <img class="grid__image" src="{{ manu.get_image_path() }}" alt="{{ manu.name }} auswählen">
                            {% endif %}
                            <div>{{ device.name }}</div>
                        </a>
                    </div>
                {% endfor %}
        </div>
    </section>
</div>
{% endblock %}

project/client/templates/main/series.html
{% extends "_base.html" %}
{% block meta %}
    {% set name_string = series_names|join(", ") %}
    <meta name="description" content="{{ name_string }} Reparatur  in Kiel, Schwentinental, Lübeck bei ▷ Smartphoniker ✓alle Modelle ✓beste Qualität ✓schneller Service ✓ohne Termin ✆ kostenlose Beratung.">
    <meta property="og:title" content="{{ name_string }} Smartphone Reparatur Kiel, Schwentinental, Lübeck | Smartphoniker">
    <meta property="og:description" content="{{ name_string }} Reparatur bei ▷ Smartphoniker ✓alle Modelle ✓beste Qualität ✓schneller Service ✓ohne Termin ✆ kostenlose Beratung.">
    <meta property="og:site_name" content="Smartphoniker - Ihr Service Partner für Smartphone, Tablet oder PC">

    <meta name="twitter:description" content="{{ name_string }} Reparatur bei ▷ Smartphoniker ✓alle Modelle ✓beste Qualität ✓schneller Service ✓ohne Termin ✆ kostenlose Beratung.">
    <meta name="twitter:title" content="{{ name_string }} Reparatur Kiel, Schwentinental, Lübeck | Smartphoniker">
{% endblock %}

{% block content %}
    <div class="container container--small">
        <section class="hero">
            <h1 class="hero__heading">Alle Hersteller</h1>
            <p class="hero__chronic hide-mobile">
                <a class="hero__chroniclink" href="{{ url_for('main.manufacturer') }}">Hersteller auswählen</a>
            </p>
            <div class="progressbar">
                <div class="progressbar__step">
                    <div class="progressbar__number progressbar__number--active">1</div>
                    <div class="progressbar__text">Hersteller wählen</div>
                </div>
                <div class="progressbar__divider"></div>
                <div class="progressbar__step">
                    <div id="STEP2" class="progressbar__number progressbar__number--active">2</div>
                    <div class="progressbar__text">Modellreihe bestimmen</div>
                </div>
                <div class="progressbar__divider"></div>
                <div class="progressbar__step">
                    <div id="STEP3" class="progressbar__number">3</div>
                    <div class="progressbar__text">Gerät auswählen</div>
                </div>
            </div>
        </section>
    </div>

    <div class="container container--small">
        <section class="grid">
            <h2 class="grid__heading">Modellreihe wählen</h2>
            <div class="grid__content">
                {% for seria in series %}
                    <div class="grid__item">
                        <a class="grid__link" href="{{ url_for('main.all_devices_of_series', manufacturer_name=manufacturer, series_name=seria.name) }}">
                            <div>{{ seria.name }}</div>
                        </a>
                    </div>
                {% endfor %}
            </div>
            {% if not series|length %}
                <p class="grid__nodevices">Aktuell bieten wir keine Festpreise für Reparaturen dieses Herstellers an. Melden Sie sich gerne bei unserem <a class="grid__link grid__link--inline" href="{{ url_for('main.faq', q='38') }}">Kundenservice</a>, wenn Sie an einer Reparatur interessiert sind.</p>
                <a class="grid__back" href="{{ url_for('main.manufacturer') }}">zurück zu den Herstellern</a>
            {% endif %}

        </section>
    </div>
{% endblock %}